apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: gjucf68ed-nodejs 
  janus-idp.io/tekton: gjucf68ed-nodejs
  backstage.io/kubernetes-id: gjucf68ed-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gjucf68ed-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml