apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: gjucf68ed-nodejs-gitops
  description: This is GitOps manifest for gjucf68ed-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=gjucf68ed-nodejs
    backstage.io/kubernetes-id: gjucf68ed-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: gjucf68ed-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:gjucf68ed-nodejs
